//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 PETools.rc 使用
//
#define IDD_DIALOG_MAIN                 101
#define IDI_ICON_MAINICO                102
#define IDD_DIALOG_ABOUT                103
#define IDD_DIALOG_PEEDIT               104
#define IDD_DIALOG_FILEHEAD             105
#define IDD_DIALOG_OPTHEADER            106
#define IDD_DIALOG_SECTIONS             107
#define IDD_DIALOG_DIRECTORY            108
#define IDD_DIALOG_CALCULATE            109
#define IDD_DIALOG_TIMESTAMP            125
#define IDD_DIALOG_EXPORT               129
#define IDD_DIALOG_RELOCATION           131
#define IDD_DIALOG_IMPORT               133
#define IDD_DIALOG_INJECTIMPORT         135
#define IDD_DIALOG_PROTECTOR            139
#define IDC_STATIC1                     1001
#define IDC_BUTTON_PEVIEW               1002
#define IDC_BUTTON_ABOUT                1003
#define IDC_BUTTON_QUIT                 1004
#define IDC_LIST_PROCESS                1005
#define IDC_LIST_MODULE                 1006
#define IDC_STATIC_COPYRIGHT            1007
#define IDC_BUTTON_FILEHEADER           1008
#define IDC_BUTTON_OPTHEADER            1009
#define IDC_BUTTON_SECTIONS             1010
#define IDC_BUTTON_DIRECTORIES          1011
#define IDC_EDIT_ENTRY                  1012
#define IDC_EDIT_IMAGEBASE              1013
#define IDC_EDIT_ENTRY2                 1013
#define IDC_EDIT_RAWPROCESS             1013
#define IDC_EDIT_IMAGESIZE              1014
#define IDC_EDIT_OPTHEADERSIZE          1015
#define IDC_EDIT_CODEBASE               1016
#define IDC_EDIT_DATABASE               1017
#define IDC_EDIT_SECTIONSIZE            1018
#define IDC_EDIT_SECTIONALIGN           1019
#define IDC_EDIT_FILEALIGN              1020
#define IDC_EDIT_CHARACT                1021
#define IDC_EDIT_HEADERSIZE             1022
#define IDC_EDIT_DIRSIZE                1023
#define IDC_EDIT_TIMESTAMP              1024
#define IDC_EDIT_SUBSYS                 1025
#define IDC_BUTTON_DOSHEADER            1026
#define IDC_BUTTON_CALCFOA              1030
#define IDC_BUTTON_PROTECT              1031
#define IDC_BUTTON_INJECT               1033
#define IDC_EDIT_MACHINE                1036
#define IDC_EDIT_SECTIONS               1037
#define IDC_EDIT_TIMEDATA               1038
#define IDC_EDIT_POINTER                1039
#define IDC_EDIT_COFFTABLE              1040
#define IDC_EDIT_OPTSIZE                1041
#define IDC_EDIT_CHA                    1042
#define IDC_BUTTON_DETAILDATA           1044
#define IDC_BUTTON_DATAEXCHANGE         1045
#define IDC_BUTTON_DETAILCHA            1045
#define IDC_BUTTON_COMPARE              1046
#define IDC_BUTTON_SAVE                 1047
#define IDC_EDIT_OPTMAGIC               1048
#define IDC_EDIT_OPTMAJORLINK           1049
#define IDC_EDIT_OPTMINORLINK           1050
#define IDC_EDIT_OPTCODESIZE            1051
#define IDC_EDIT_OPTINITDATA            1052
#define IDC_EDIT_OPTUNINITDATA          1053
#define IDC_EDIT_OPTENTRY               1054
#define IDC_EDIT_OPTCODEBASE            1055
#define IDC_EDIT_OPTDATABASE            1056
#define IDC_EDIT_OPTIMAGEBASE           1057
#define IDC_EDIT_OPTSECALIGN            1058
#define IDC_EDIT_OPTFILEALIGN           1059
#define IDC_EDIT_OPTMAJOROS             1060
#define IDC_EDIT_OPTMINOROS             1061
#define IDC_EDIT_OPTMAJORIMAGE          1062
#define IDC_EDIT_OPTMINORIMAGE          1063
#define IDC_EDIT_OPTMAJORSUBSYS         1064
#define IDC_EDIT_OPTMINORSUBSYS         1065
#define IDC_EDIT_OPTWINVERSION          1066
#define IDC_EDIT_OPTIMAGESIZE           1067
#define IDC_EDIT_OPTHEADERSSIZE         1068
#define IDC_EDIT_OPTCHECK               1069
#define IDC_EDIT_OPTSUBSYS              1070
#define IDC_EDIT_OPTDLLCHA              1071
#define IDC_EDIT_OPTSTACKRES            1072
#define IDC_EDIT_OPTSTACKCOM            1073
#define IDC_EDIT_OPTHEAPRES             1074
#define IDC_EDIT_OPTHEAPCOM             1075
#define IDC_EDIT_OPTFLAGS               1076
#define IDC_EDIT_OPTRVAANDSIZE          1077
#define IDC_LIST_SECTION                1078
#define IDC_EDIT_EXPORTRAV              1079
#define IDC_EDIT_EXPORTSIZE             1080
#define IDC_EDIT_IMPORTRAV              1081
#define IDC_EDIT_IMPORTSIZE             1082
#define IDC_EDIT_TimeEncode             1082
#define IDC_EDIT_RESOURCERVA            1083
#define IDC_EDIT_TimeYMD                1083
#define IDC_EDIT_RESOURCESIZE           1084
#define IDC_EDIT_TimeHMS                1084
#define IDC_EDIT_EXCEPTIONRVA           1085
#define IDC_EDIT_EXCEPTIONSIZE          1086
#define IDC_EDIT_SECURITYRVA            1087
#define IDC_EDIT_SECURITYSIZE           1088
#define IDC_EDIT_EXP_CHA                1088
#define IDC_EDIT_RELOCATIONRVA          1089
#define IDC_EDIT_EXP_TIME               1089
#define IDC_EDIT_RELOCATIONSIZE         1090
#define IDC_EDIT_EXP_BASE               1090
#define IDC_EDIT_DEBUGRVA               1091
#define IDC_EDIT_EXP_NAMEOFFSET         1091
#define IDC_EDIT_DEBUGSIZE              1092
#define IDC_EDIT_EXP_NAME               1092
#define IDC_EDIT_ASDRVA                 1093
#define IDC_EDIT_EXP_NUMFUNC            1093
#define IDC_EDIT_ASDSIZE                1094
#define IDC_EDIT_EXP_NUMNAME            1094
#define IDC_EDIT_RVAGPRVA               1095
#define IDC_EDIT_EXP_ADDRFUNC           1095
#define IDC_EDIT_RVAGPSIZE              1096
#define IDC_EDIT_EXP_ADDRNAME           1096
#define IDC_EDIT_TLSRVA                 1097
#define IDC_EDIT_EXP_ADDRORD            1097
#define IDC_EDIT_TLSSIZE                1098
#define IDC_EDIT_LOADRVA                1099
#define IDC_LIST_EXP_FUNC               1099
#define IDC_EDIT_LOADSIZE               1100
#define IDC_EDIT_BOUNDRVA               1101
#define IDC_EDIT_BOUNDSIZE              1102
#define IDC_EDIT_IATRVA                 1103
#define IDC_EDIT_IATSIZE                1104
#define IDC_EDIT_DELAYRVA               1105
#define IDC_EDIT_DELAYSIZE              1106
#define IDC_EDIT_COMRVA                 1107
#define IDC_EDIT_COMSIZE                1108
#define IDC_EDIT_RESERVEDRVA            1109
#define IDC_EDIT_RESERVEDSIZE           1110
#define IDC_EDIT_LOCATE                 1111
#define IDC_BUTTON_EXPORT               1111
#define IDC_EDIT_VA                     1112
#define IDC_LIST_RELO_BLOCK             1112
#define IDC_BUTTON_RELOCATION           1112
#define IDC_EDIT_RVA                    1113
#define IDC_LIST_RELO_BLOCKITEM         1113
#define IDC_BUTTON_IMPORT               1113
#define IDC_EDIT_FOA                    1114
#define IDC_LIST_IMP_MAIN               1114
#define IDC_RADIO_VA                    1115
#define IDC_LIST_IMP_FUNC               1115
#define IDC_RADIO_RVA                   1116
#define IDC_RADIO_FOA                   1117
#define IDC_BUTTON_DLLSELECT            1117
#define IDC_BUTTON_CALC                 1118
#define IDC_EDIT_INJECTDLL              1118
#define IDC_EDIT_IMJECTFUNC             1119
#define IDC_BUTTON_PROTECTOR            1121
#define IDC_BUTTON_RAWPROCESS           1123
#define IDC_BUTTON3                     1124
#define IDC_BUTTON_ENCODE               1124
#define IDC_BUTTON_PROTECTPROCESS       1124
#define IDC_EDIT_PROTECTOR              1125

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
